### ISSUE TITLE
YAML support for marathon-cli

### ISSUE THREAD

**Issue by navidurrahman** [thefactory/marathon-python#74]
I need a marathon-cli with YAML support. Should I add the functionality and open a pull request? 

Previously, I opened a pull request of chronos-python, but looks like asher is away these days.

**Comment by navidurrahman** [comment]
@solarkennedy ^^

**Comment by solarkennedy** [comment]
Yea, I think it wouldn't be that much feature creep to have a CLI, but I would be very skeptical if it did any more than just post the yaml contents. It will be a lot of upkeep if we have to constantly add a billion cli arguments.

**Comment by navidurrahman** [comment]
I agree with you in a way, but look at the example below, and let me know your thoughts.

```bash
./bin/marathon create -y apps/apps.yaml -d ubuntu/image:tag -e env_file
```

```yaml
- id: uae-celery
  cpus: 0.65
  mem: 2048
  cmd: "sleep 100"
  volumes:
    - container_path: "/home/user/logs/"
      host_path: "/var/log"
```

We are trying to separate data files from code, and it can be useful from any admin machine.

Regarding multiple arguments, i guess few functions should be fine.
